---
title: "P8105 Homework 5"
author: "Apoorva Srinivasan"
date: "11/.3/2018"
output: github_document
---


##PROBLEM 1
```{r setup, include=FALSE}
library(tidyverse)
```



```{r, include = FALSE}
p1_data = list.files("./data", full.names = TRUE) 

p1_df = map(p1_data, read_csv) 

for (i in 1:20) {
  if (i < 11) {
    p1_df[[i]] = p1_df[[i]] %>% 
    mutate(study_id = i, arm = "Control")
  } else if (i > 10) {
    p1_df[[i]] = p1_df[[i]] %>% 
      mutate(study_id = i - 10, arm = "Experimental")
  }
}

```


```{r}
p1_tidy = p1_df %>%
  bind_rows() %>%
  gather(key = week, value = observation, week_1:week_8) %>%
  separate(week, into = c("delete", "week"), sep = "_") %>%
  select(study_id, arm, everything(), -(delete)) %>%
  arrange(study_id, week) %>%
  mutate(week = as.integer(week), 
         study_id = as.character(study_id))

p1_tidy

```


Spaghetti plot

```{r}
p1_tidy %>%
  group_by(arm, study_id) %>% 
  ggplot(aes(x = week, y = observation, color = arm, type = study_id)) + 
    geom_line() +
  labs(title = "Observations on each subject over time",
       x = "Week", 
       y = "Observation")
```



##PROBLEM 2


```{r}
homicide = read_csv("./homicide-data.csv")
```

```{r}
homicide = homicide %>%
   mutate(city_state = str_c(city, ", ", state),
         disposition = as.factor(disposition))

```

```{r}
homicide_group = homicide %>%
  group_by(city_state) %>%
  summarise(n_total = n(),
  n_unsolved = sum(disposition %in% c("Closed without arrest", "Open/No arrest")))
  
```

```{r, message = FALSE}
homicide_balt = homicide_group %>%
  filter(city_state == "Baltimore, MD") 
  prop.test(homicide_balt$n_unsolved, homicide_balt$n_total) %>%
  broom::tidy() %>%
    select(estimate, conf.low, conf.high) %>% 
  knitr::kable()
 
  homicide_balt
```

Developing a function and iterating
```{r}
prop_city = function(x, y){
  
  prop.test(x,y) %>% 
    broom::tidy() %>% 
  select(estimate, conf.low, conf.high)
  
  
  
}

prop_city<-map2(.x = homicide_group$n_unsolved, .y = homicide_group$n_total, ~prop_city(.x, .y)) %>% 
  bind_rows() %>% 
  mutate(city_state = homicide_group$city_state) %>% 
  select(city_state, everything()) 

prop_city
```


Plot:


```{r}
prop_city %>% 
  ggplot(aes(x = fct_reorder(city_state, estimate), y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 80, hjust = 1))+
  labs(
    title = "Estimates and CIs for Each City",
    x = "City, State",
    y = "Estimates" )
```

